# Generated by Django 4.1.1 on 2022-09-28 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=40)),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('battery_level', models.FloatField(default=100.0)),
                ('notification_update', models.DateTimeField(blank=True, null=True)),
                ('meters', models.IntegerField(default=0)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('on_maintenance', models.BooleanField(default=False)),
                ('vacant', models.BooleanField(default=True)),
            ],
        ),
    ]
